Quit = "ctrl+c"
Submit = "enter"
MoveToLeft = "left"
MoveToRight = "right"
VimMoveLeft = "h"
VimMoveRight = "l"
VolumeUp = "up"
VolumeDown = "down"
NextSong = "ctrl+right"
PrevSong = "ctrl+left"
Delete = "d"
PauseSong = " "
GoBack = "esc"
ToggleHelp = "?"